# Generated by Django 3.1.7 on 2022-09-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun', '0002_auto_20220915_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('score', models.IntegerField()),
                ('at', models.IntegerField()),
            ],
        ),
    ]
