# Generated by Django 3.1.7 on 2022-09-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun', '0003_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='uphoto',
            field=models.ImageField(default=100, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fun',
            name='exp',
            field=models.TextField(default=50),
            preserve_default=False,
        ),
    ]
