# Generated by Django 4.1.1 on 2022-09-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun', '0004_auto_20220926_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='maths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.TextField()),
                ('choi1', models.TextField()),
                ('choi2', models.TextField()),
                ('choi3', models.TextField()),
                ('choi4', models.TextField()),
                ('ans', models.TextField()),
                ('exp', models.TextField()),
            ],
        ),
    ]
